language: node_js

node_js:
  - "lts/*"

install:
  - npm install 

before_script:
  - ganache-cli > /dev/null &
  - sleep 5

script:
  - npm test

after_script:
  - npm run coverage && cat coverage/lcov.info | coveralls
  