language: node_js

node_js:
  - "lts/*"

install:
  - npm install 
  - npm install -g truffle
  - npm install -g ethereumjs-testrpc

before_script:
  - testrpc > /dev/null &
  - sleep 5

script:
  - ./node_modules/.bin/solidity-coverage

after_script:
  - cat coverage/lcov.info | coveralls
